version: '3.8'

services:
  price_db:
    image: mysql:8.0
    container_name: price_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: price_db
    ports:
      - "3307:3306"   # host:container
    volumes:
      - price_db_data:/var/lib/mysql

  fundamentals_db:
    image: mysql:8.0
    container_name: fundamentals_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: fundamentals_db
    ports:
      - "3308:3306"
    volumes:
      - fundamentals_db_data:/var/lib/mysql

volumes:
  price_db_data:
  fundamentals_db_data:
